project:
  type: website
  output-dir: docs

# Meta
description-meta: "Quarto Academic Website Template adapted by Dr. Gang He"
author-meta: "Dr. Gang He"
website:
  title: "Xinyi Bai" # 或者是 Quarto Academic
  navbar:
    background: light
    left:
      - text: "About"
        menu:
          - text: "About Me"
            file: index.qmd
          - text: "Volunteering"
            file: volunteering.qmd
          - text: "Contact"
            file: contact.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Rotations"
        menu:
          - text: "Overall"
            file: rotations/overall.qmd
          - text: "Internal Medicine"
            file: rotations/internal-medicine.qmd
          - text: "Physical Medicine"
            file: rotations/physical-medicine.qmd
      - text: "Interests"
        menu:
          - text: "Running"
            file: interests/running.qmd
          - text: "Travel"
            file: interests/travel.qmd

    right: 
      - text: CV
        href: CV_Xinyi_Bai_Chinese.pdf
      
  
  page-navigation: true
  
  page-footer: 
    left: "[Xinyi Bai](https://github.com/jasbai2004-tech) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "*If in doubt go flat out*"
    right:  
      - icon: github
        href: https://github.com/jasbai2004-tech
        target: _blank
      - icon: envelope
        href: mailto:jasminebai2004@outlook.com  
        target: _blank
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/drganghe/quarto-academic-website-template
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://drganghe.github.io/quarto-academic-website-template"
  
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

